#!/bin/bash
make code_08049DF4.o
make movement.o
make menu/figurineMenu.o
make menu/kinstoneMenu.o
make menu/pauseMenuScreen6.o
make menu/pauseMenu.o
make flagDebug.o
make code_08049CD4.o
make scroll.o
make itemDefinitions.o
make game.o
make vram.o
make playerItemUtils.o
make code_0805EC04.o
make fade.o
make objectUtils.o
make main.o
make itemUtils.o
make demo.o
make subtask.o
make gba/m4a.o
make playerItem/playerItemPacciCane.o
make playerItem/playerItemFireRodProjectile.o
make playerItem/playerItemSwordBeam.o
make playerItem/playerItemPacciCaneProjectile.o
make playerItem/playerItemGust.o
make playerItem/playerItemCellOverwriteSet.o
make playerItem/playerItemHeldObject.o
make playerItem/playerItemBottle.o
make playerItem/playerItemSword.o
make playerItem/playerItemLantern.o
make playerItem/playerItemGustBig.o
make playerItem/playerItemDashSword.o
make playerItem/playerItemBomb.o
make playerItem/playerItemBoomerang.o
make playerItem/playerItemShield.o
make playerItem/playerItemGustJar.o
make playerItem/playerItemSpiralBeam.o
make playerItem/playerItemBow.o
make object/lightableSwitch.o
make object/specialChest.o
make object/crenelBeanSprout.o
make object/fan.o
make object/windTribeTeleporter.o
make object/sanctuaryStoneTablet.o
make object/angryStatue.o
make object/bigVortex.o
make object/bakerOven.o
make object/octorokBossObject.o
make object/vaati3PlayerObject.o
make object/macroMushroomStalk.o
make object/lavaPlatform.o
make object/thoughtBubble.o
make object/minishPortalStone.o
make object/paper.o
make object/vaati1Portal.o
make object/gyorgBossObject.o
make object/lampParticle.o
make object/fileScreenObjects.o
make object/linkFire.o
make object/litArea.o
make object/whirlwind.o
make object/object53.o
make object/floatingBlock.o
make object/jailBars.o
make object/elementsBackground.o
make object/houseSign.o
make object/ladderHoleInBookshelf.o
make object/dirtParticle.o
make object/macroBook.o
make object/pushableFurniture.o
make object/mazaalBossObject.o
make object/bell.o
make object/lilypadLargeFalling.o
make object/houseDoorExterior.o
make object/figurineDevice.o
make object/pushableStatue.o
make object/gentariCurtain.o
make object/pressurePlate.o
make object/bench.o
make object/ezloCapFlying.o
make object/linkEmptyingBottle.o
make object/giantRock.o
make object/itemOnGround.o
make object/windcrest.o
make object/objectA2.o
make object/bigIceBlock.o
make object/rupee.o
make object/macroDecorations.o
make object/minishEmoticon.o
make object/giantTwig.o
make object/chuchuBossStartParticle.o
make object/greatFairy.o
make object/guruguruBar.o
make object/carlovObject.o
make object/bossDoor.o
make object/fourElements.o
make object/lightRay.o
make object/object1F.o
make object/cloud.o
make object/objectOnPillar.o
make object/eyeSwitch.o
make object/waterDropObject.o
make object/shrinkingHieroglyphs.o
make object/mulldozerSpawnPoint.o
make object/steam.o
make object/graveyardKey.o
make object/pullableMushroom.o
make object/linkHoldingItem.o
make object/lockedDoor.o
make object/minishVillageObject.o
make object/heartContainer.o
make object/thunderbolt.o
make object/bigPushableLever.o
make object/whiteTriangleEffect.o
make object/beanstalk.o
make object/keyStealingTakkuri.o
make object/unusedSkull.o
make object/playerClone.o
make object/ladderUp.o
make object/doubleBookshelf.o
make object/ezloCap.o
make object/trapdoor.o
make object/objectA8.o
make object/bigBarrel.o
make object/pushableLever.o
make object/object70.o
make object/well.o
make object/bird.o
make object/cabinFurniture.o
make object/minishPortalCloseup.o
make object/vaati3Death.o
make object/rotatingTrapdoor.o
make object/object37.o
make object/frozenOctorok.o
make object/lamp.o
make object/barrelSpiderweb.o
make object/treeHidingPortal.o
make object/macroPlayer.o
make object/swordsmanNewsletter.o
make object/vaati2Particle.o
make object/frozenFlower.o
make object/hittableLever.o
make object/gleerokParticle.o
make object/board.o
make object/railtrack.o
make object/lightDoor.o
make object/smallIceBlock.o
make object/chuchuBossCutscene.o
make object/mask.o
make object/minecart.o
make object/frozenWaterElement.o
make object/minishSizedArchway.o
make object/giantRock2.o
make object/itemForSale.o
make object/minishSizedEntrance.o
make object/furniture.o
make object/object1D.o
make object/gustJarParticle.o
make object/fanWind.o
make object/windTribeFlag.o
make object/warpPoint.o
make object/objectA.o
make object/giantBookLadder.o
make object/cuccoMinigame.o
make object/minecartDoor.o
make object/enemyItem.o
make object/object30.o
make object/hiddenLadderDown.o
make object/objectBF.o
make object/chestSpawner.o
make object/backgroundCloud.o
make object/picoBloom.o
make object/mazaalObject.o
make object/moleMittsParticle.o
make object/deathFx.o
make object/lilypadLarge.o
make object/kinstoneSpark.o
make object/object63.o
make object/button.o
make object/book.o
make object/bedCover.o
make object/stoneTablet.o
make object/smoke.o
make object/fireplace.o
make object/floatingPlatform.o
make object/giantLeaf.o
make object/vaati3Arm.o
make object/swordParticle.o
make object/linkAnimation.o
make object/palaceArchway.o
make object/crackingGround.o
make object/hitSwitch.o
make object/macroShoe.o
make object/fireballChain.o
make object/pushableRock.o
make object/pinwheel.o
make object/cutsceneOrchestrator.o
make object/macroAcorn.o
make object/treeThorns.o
make object/cameraTarget.o
make object/objectA7.o
make object/japaneseSubtitle.o
make object/pushableGrave.o
make object/specialFx.o
make object/bush.o
make object/objectOnSpinyBeetle.o
make object/fairy.o
make object/metalDoor.o
make object/titleScreenObject.o
make object/flame.o
make object/pullableLever.o
make object/minishLight.o
make object/objectBlockingStairs.o
make object/evilSpirit.o
make object/archway.o
make object/chuchuBossParticle.o
make object/pot.o
make object/lilypadSmall.o
make object/barrelInside.o
make object/mineralWaterSource.o
make object/waterfallOpening.o
make object/smokeParticle.o
make object/waterElement.o
make object/blockPushed.o
make object/parallaxRoomView.o
make object/cutsceneMiscObject.o
make object/bollard.o
make object/ambientClouds.o
make object/jarPortal.o
make object/houseDoorInterior.o
make entity.o
make data/caveBorderMapData.o
make data/mapActTileToSurfaceType.o
make data/transitions.o
make data/objPalettes.o
make data/figurineMenuData.o
make data/hitbox.o
make data/screenTransitions.o
make data/areaMetadata.o
make data/data_080046A4.o
make item/itemShield.o
make item/itemGustJar.o
make item/itemBoomerang.o
make item/itemJarEmpty.o
make item/itemPacciCane.o
make item/itemMoleMitts.o
make item/itemRocsCape.o
make item/itemBow.o
make item/itemSword.o
make item/itemPegasusBoots.o
make item/itemOcarina.o
make item/itemBomb.o
make item/itemLantern.o
make item/itemTryPickupObject.o
make item/itemDebug.o
make enemy.o
make projectile.o
make fileselect.o
make enemyUtils.o
make backgroundAnimations.o
make debug.o
make room.o
make color.o
make message.o
make gameOverTask.o
make projectileUtils.o
make cutscene.o
make sineTable.o
make item.o
make gameData.o
make npc.o
make playerUtils.o
make projectile/v3TennisBallProjectile.o
make projectile/projectile5.o
make projectile/v3ElectricProjectile.o
make projectile/removableDust.o
make projectile/keatonDagger.o
make projectile/darkNutSwordSlash.o
make projectile/moblinSpear.o
make projectile/torchTrapProjectile.o
make projectile/v1DarkMagicProjectile.o
make projectile/spiderWeb.o
make projectile/spikedRollers.o
make projectile/v1FireProjectile.o
make projectile/gyorgTail.o
make projectile/lakituLightning.o
make projectile/lakituCloudProjectile.o
make projectile/dekuSeedProjectile.o
make projectile/dirtBallProjectile.o
make projectile/gleerokProjectile.o
make projectile/boneProjectile.o
make projectile/iceProjectile.o
make projectile/v1EyeLaser.o
make projectile/mandiblesProjectile.o
make projectile/guardLineOfSight.o
make projectile/arrowProjectile.o
make projectile/rockProjectile.o
make projectile/v3HandProjectile.o
make projectile/guruguruBarProjectile.o
make projectile/ballAndChain.o
make projectile/winder.o
make projectile/v2Projectile.o
make projectile/mazaalEnergyBeam.o
make projectile/cannonballProjectile.o
make projectile/octorokBossProjectile.o
make projectile/stalfosProjectile.o
make projectile/windProjectile.o
make projectile/fireProjectile.o
make projectile/gyorgMaleEnergyProjectile.o
make affine.o
make flags.o
make roomInit.o
make common.o
make title.o
make playerHitbox.o
make beanstalkSubtask.o
make save.o
make npcDefinitions.o
make playerItemDefinitions.o
make physics.o
make sound.o
make player.o
make playerItem.o
make kinstone.o
make gameUtils.o
make droptables.o
make script.o
make npcUtils.o
make eeprom.o
make staffroll.o
make manager.o
make enterPortalSubtask.o
make interrupts.o
make npcFunctions.o
make ui.o
make subtask/subtaskFastTravel.o
make subtask/subtaskWorldEvent.o
make subtask/subtaskAuxCutscene.o
make subtask/subtaskMapHint.o
make subtask/subtaskLocalMapHint.o
make screenTileMap.o
make object.o
make enemy/octorokGolden.o
make enemy/vaatiWrathEye.o
make enemy/torchTrap.o
make enemy/curtain.o
make enemy/enemy50.o
make enemy/rope.o
make enemy/spinyBeetle.o
make enemy/miniFireballGuy.o
make enemy/gyorgChild.o
make enemy/peahat.o
make enemy/moldworm.o
make enemy/waterDrop.o
make enemy/rupeeLike.o
make enemy/ropeGolden.o
make enemy/moldorm.o
make enemy/gyorgFemaleEye.o
make enemy/helmasaur.o
make enemy/rollobite.o
make enemy/beetle.o
make enemy/keese.o
make enemy/tektiteGolden.o
make enemy/wizzrobeWind.o
make enemy/armos.o
make enemy/eyegore.o
make enemy/gyorgMaleEye.o
make enemy/likeLike.o
make enemy/bombPeahat.o
make enemy/spikedBeetle.o
make enemy/dust.o
make enemy/sensorBladeTrap.o
make enemy/slime.o
make enemy/octorokBoss.o
make enemy/doorMimic.o
make enemy/vaatiArm.o
make enemy/enemyE.o
make enemy/ballChainSoldier.o
make enemy/enemy64.o
make enemy/bowMoblin.o
make enemy/wizzrobeIce.o
make enemy/gyorgFemaleMouth.o
make enemy/mazaalMacro.o
make enemy/chuchu.o
make enemy/rockChuchu.o
make enemy/mulldozer.o
make enemy/takkuri.o
make enemy/treeItem.o
make enemy/keaton.o
make enemy/flyingSkull.o
make enemy/vaatiEyesMacro.o
make enemy/enemy4D.o
make enemy/gyorgMale.o
make enemy/fireballGuy.o
make enemy/wizzrobeFire.o
make enemy/madderpillar.o
make enemy/tektite.o
make enemy/sub_080451CC.o
make enemy/bombarossa.o
make enemy/gibdo.o
make enemy/wisp.o
make enemy/acroBandits.o
make enemy/mazaalHead.o
make enemy/vaatiWrath.o
make enemy/mazaalHand.o
make enemy/vaatiTransfiguredEye.o
make enemy/chaser.o
make enemy/mazaalBracelet.o
make enemy/flyingPot.o
make enemy/stalfos.o
make enemy/darkNut.o
make enemy/smallPesto.o
make enemy/miniSlime.o
make enemy/crow.o
make enemy/gyorgFemale.o
make enemy/hangingSeed.o
make enemy/lakitu.o
make enemy/lakituCloud.o
make enemy/businessScrubPrologue.o
make enemy/fallingBoulder.o
make enemy/sluggula.o
make enemy/bladeTrap.o
make enemy/wallMaster2.o
make enemy/wallMaster.o
make enemy/leever.o
make enemy/cuccoAggr.o
make enemy/cloudPiranha.o
make enemy/enemy66.o
make enemy/ghini.o
make enemy/bobomb.o
make enemy/cuccoChickAggr.o
make enemy/gleerok.o
make enemy/vaatiBall.o
make enemy/businessScrub.o
make enemy/puffstool.o
make enemy/spinyChuchu.o
make enemy/scissorsBeetle.o
make enemy/vaatiProjectile.o
make enemy/octorok.o
make enemy/spearMoblin.o
make enemy/chuchuBoss.o
make enemy/vaatiRebornEnemy.o
make enemy/vaatiTransfigured.o
make enemy/pesto.o
make enemy/spark.o
make objectDefinitions.o
make manager/bridgeManager.o
make manager/vaati3BackgroundManager.o
make manager/rollingBarrelManager.o
make manager/regionTriggerManager.o
make manager/minishPortalManager.o
make manager/steamOverlayManager.o
make manager/powBackgroundManager.o
make manager/lightManager.o
make manager/enterRoomTextboxManager.o
make manager/horizontalMinishPathBackgroundManager.o
make manager/cameraTargetManager.o
make manager/animatedBackgroundManager.o
make manager/waterfallBottomManager.o
make manager/destructibleTileObserveManager.o
make manager/entitySpawnManager.o
make manager/secretManager.o
make manager/cloudStaircaseTransitionManager.o
make manager/ezloHintManager.o
make manager/miscManager.o
make manager/moveableObjectManager.o
make manager/railIntersectionManager.o
make manager/flagAndOperatorManager.o
make manager/minishRaftersBackgroundManager.o
make manager/fightManager.o
make manager/lightRayManager.o
make manager/hyruleTownTileSetManager.o
make manager/pushableFurnitureManager.o
make manager/staticBackgroundManager.o
make manager/minishVillageTileSetManager.o
make manager/enemyInteractionManager.o
make manager/delayedEntityLoadManager.o
make manager/manager29.o
make manager/vaatiAppearingManager.o
make manager/flameManager.o
make manager/verticalMinishPathBackgroundManager.o
make manager/holeManager.o
make manager/fallingItemManager.o
make manager/weatherChangeManager.o
make manager/lightLevelSetManager.o
make manager/houseSignManager.o
make manager/cloudOverlayManager.o
make manager/vaati3InsideArmManager.o
make manager/rainfallManager.o
make manager/floatingPlatformManager.o
make manager/repeatedSoundManager.o
make manager/bombableWallManager.o
make manager/tileChangeObserveManager.o
make manager/templeOfDropletsManager.o
make manager/angryStatueManager.o
make manager/specialWarpManager.o
make manager/diggingCaveEntranceManager.o
make manager/minishSizedEntranceManager.o
make manager/vaati3StartManager.o
make manager/armosInteriorManager.o
make manager/goronMerchantShopManager.o
make manager/hyruleTownBellManager.o
make manager/tilePuzzleManager.o
make itemMetaData.o
make collision.o
make text.o
make worldEvent/worldEvent10.o
make worldEvent/worldEvent4.o
make worldEvent/worldEvent25.o
make worldEvent/worldEvent12.o
make worldEvent/worldEvent24.o
make worldEvent/worldEvent13.o
make worldEvent/worldEvent16.o
make worldEvent/worldEvent21.o
make worldEvent/worldEvent15.o
make worldEvent/worldEvent22.o
make worldEvent/worldEvent5.o
make worldEvent/worldEvent14.o
make worldEvent/worldEvent20.o
make worldEvent/worldEvent2.o
make worldEvent/worldEvent11.o
make worldEvent/worldEvent17.o
make worldEvent/worldEvent8.o
make worldEvent/worldEvent19.o
make worldEvent/worldEvent9.o
make worldEvent/worldEvent7.o
make worldEvent/worldEvent3.o
make worldEvent/worldEvent6.o
make worldEvent/worldEvent1.o
make worldEvent/worldEvent0.o
make worldEvent/worldEvent23.o
make npc/percy.o
make npc/cow.o
make npc/goron.o
make npc/rem.o
make npc/townsperson.o
make npc/castorWildsStatue.o
make npc/festari.o
make npc/emma.o
make npc/drLeft.o
make npc/syrup.o
make npc/mutoh.o
make npc/npc23.o
make npc/townMinish.o
make npc/mailbox.o
make npc/bigGoron.o
make npc/wheaton.o
make npc/vaati.o
make npc/npc9.o
make npc/forestMinish.o
make npc/postman.o
make npc/minishEzlo.o
make npc/librarians.o
make npc/talon.o
make npc/pita.o
make npc/smallTownMinish.o
make npc/ezlo.o
make npc/librari.o
make npc/hurdyGurdyMan.o
make npc/goronMerchant.o
make npc/malon.o
make npc/npc4F.o
make npc/dampe.o
make npc/farore.o
make npc/ghostBrothers.o
make npc/melari.o
make npc/kingDaltus.o
make npc/dog.o
make npc/nayru.o
make npc/anju.o
make npc/carlov.o
make npc/milkCart.o
make npc/ministerPotho.o
make npc/pina.o
make npc/beedle.o
make npc/castleMaid.o
make npc/mountainMinish.o
make npc/sturgeon.o
make npc/cat.o
make npc/zeldaFollower.o
make npc/tingleSiblings.o
make npc/carpenter.o
make npc/gina.o
make npc/guardWithSpear.o
make npc/phonograph.o
make npc/picolyteBottle.o
make npc/stamp.o
make npc/din.o
make npc/smith.o
make npc/marcy.o
make npc/npc5.o
make npc/bladeBrothers.o
make npc/clothesRack.o
make npc/npc58.o
make npc/npc26.o
make npc/windTribespeople.o
make npc/brocco.o
make npc/kid.o
make npc/kingGustaf.o
make npc/mayorHagen.o
make npc/simon.o
make npc/stockwell.o
make npc/npc4E.o
make npc/vaatiReborn.o
make npc/cucco.o
make npc/guard.o
make npc/epona.o
make npc/cuccoChick.o
make npc/gregal.o
make npc/zelda.o
make npc/sittingPerson.o
make npc/gentari.o
make npc/moblinLady.o
make npc/fusionMenuNPC.o
make npc/farmers.o
make npc/gorman.o
make npc/mama.o
make npc/teachers.o
